s1 = { '1', '2', '3'} to s1 = {1, 2, 3}

In [1]:
listelm = ['sworna','vidhya','mahadevan']
enm = enumerate(listelm)
print(enm)
print(list(enm))

[(0, 'sworna'), (1, 'vidhya'), (2, 'mahadevan')]


In [2]:
listelm = ['sworna','vidhya','mahadevan']
enm = enumerate(listelm, 8)
print(enm)
print(list(enm))

[(8, 'sworna'), (9, 'vidhya'), (10, 'mahadevan')]


In [3]:
my_str = "Welcome you all to ta session on 9th 2022"
#''.join(list(map(lambda x:x.upper(),my_str)))
print(my_str.upper())

WELCOME YOU ALL TO TA SESSION ON 9TH 2022


In [4]:
def u_case(str):
    return str.upper()
print(''.join(list((map(u_case,my_str)))))

WELCOME YOU ALL TO TA SESSION ON 9TH 2022


In [5]:
%%time

my_str = "Welcome you all to ta session on 9th 2022"
print(''.join(filter(lambda x:x.lower() not in 'aeiou',my_str)))

Wlcm y ll t t sssn n 9th 2022
Wall time: 1.2 ms


In [6]:
from functools import reduce
ans =reduce(lambda x,y: x +7*y, range(1,101))
print(ans)

35344


In [34]:
s1 = 'We are really pleased to meet you in our city'
s2 = 'The city was hit by a really heavy storm'

ans= tuple(filter(lambda x: x not in s1.split(), s2.split()))
anss= list(filter(lambda y: y in s1.split(), s2.split()))
print(ans)
print(anss)
print((ans,anss))

('The', 'was', 'hit', 'by', 'a', 'heavy', 'storm')
['city', 'really']
(('The', 'was', 'hit', 'by', 'a', 'heavy', 'storm'), ['city', 'really'])


In [35]:
s1 = 'We are really pleased to meet you in our city'
s2 = 'The city was hit by a really heavy storm'

s= set(s1.split())
ss= set(s2.split())
l= list(s.intersection(ss))
l1=list(s.symmetric_difference(ss))
print(l)
print(l1)
print((l,l1))

['really', 'city']
['was', 'pleased', 'storm', 'are', 'The', 'hit', 'in', 'heavy', 'our', 'a', 'to', 'by', 'We', 'you', 'meet']
(['really', 'city'], ['was', 'pleased', 'storm', 'are', 'The', 'hit', 'in', 'heavy', 'our', 'a', 'to', 'by', 'We', 'you', 'meet'])


In [36]:
sentence="Sworna Vidhya is the best mother of universe"
sentence[:14]+sentence[15:]

'Sworna Vidhya s the best mother of universe'

In [41]:
x=['ab','cd']
print(len(list(map(list,x))))

2


In [42]:
tuple=(2804,'Sworna')
tuple*=2
tuple

(2804, 'Sworna', 2804, 'Sworna')

In [44]:
s = a + '[' + b + ':' + c + ']'
s

NameError: name 'a' is not defined

In [49]:
b=(1,)
type(b)

tuple

#### Create an array of 10 zeros

In [2]:
import numpy as np
a= np.zeros(10, dtype= int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of the integers from 10 to 50

In [10]:
a= np.arange(11,41,2)
a

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
a= np.arange(9).reshape(3,3)
print(a)
print(a.ndim)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


Use NumPy to generate a random number between 0 and 1

In [50]:
a1= np.random.normal(0,1,1)
a1

array([1.13704113])

Create an array of 20 linearly spaced points between 0 and 1:

In [56]:
a= np.linspace(0, 1, 20)
a

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([[12, 13, 14, 15],
[17, 18, 19, 20],
[22, 23, 24, 25]])


In [3]:
newArray = np.arange(12,26) 
revisedList = [each for index, each in enumerate(newArray) if index % 5 != 4]
np.array(revisedList).reshape(3,4)


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])