In [1]:
import numpy as np

n1= np.array( [1.0, 2, 3.5, 0.2, True] )
n1

array([1. , 2. , 3.5, 0.2, 1. ])

In [4]:
array_1 = [1, 2, 3, 5, 4, 6, 7, 8, 5, 3, 2]
print(array_1[ : : -2])
 

[2, 5, 7, 4, 3, 1]


In [5]:
n = int(input())
ar= ([0,1])
arr= ([1,0])
np.tile(ar, (n//2,n//2))
np.tile(arr, (n//2,n//2))

3


array([[1, 0]])

 # CheckBoard Matrix problem


In [6]:
n= int(input())

import numpy as np

# Create the smallest unit of a checkerboard matrix
x = np.array([[0, 1], [1, 0]])

# Create a checkerboard matrix of size n*n using the tile() function. We use n//2 
# since the smallest unit of a checkerboard matrix is already of size 2*2. So, for 
# creating a larger matrix, say, of size 8, we need to replicate it using the tile()
# function 4 times as it will then give a matrix of size 8*8.
check = np.tile(x, (n//2, n//2))

# Print the created matrix
print(check)

5
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [7]:
p=[[1, 5],
 [3, 7],
 [4, 9]]
np.reshape(p, (1, -1))

array([[1, 5, 3, 7, 4, 9]])

In [9]:
a1= np.array([0,1,2,3])
a2= np.array([6,7,8,9])
print(np.vstack((a1,a2)))
np.hstack((a1,a2))

array([0, 1, 2, 3, 6, 7, 8, 9])

In [10]:
a = np.array([1, 2, 3,4,5], ndmin = 3)
print(a)

[[[1 2 3 4 5]]]


In [10]:
import numpy as np
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18])
print(arr[2:-1:2])
print(arr[-5:1:-1])
print(arr[-5:-1])
print(arr[-7:-2])

[12 14 16]
[14 13 12]
[14 15 16 17]
[12 13 14 15 16]


In [14]:
arr = np.array([[10, 11, 12, 13, 14], [15,16,17,18,19]])
arr[:,2:]


array([[12, 13, 14],
       [17, 18, 19]])

In [23]:
a1 = np.array([11,12,13])

a2 = np.array([14,15,16])
a= np.dstack((a1,a2))
print(a)

[[[11 14]
  [12 15]
  [13 16]]]


In [25]:
print(np.array(100))

100


In [1]:
import numpy as np
myArray = np.array([10, 11, 12, 13, 14])
print(myArray[0])
print(myArray[3])

10
13


In [2]:
myArray = np.array([10, 11, 12, 13, 14])
print(myArray[1] + myArray[3])
print(myArray[1] * myArray[2])

24
132


Write a code that creates a three-dimensional array for numbers from 1-30.

In [20]:
np.arange(1,31).reshape(2,3,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [12]:
np.dstack(np.arange(1,31))

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]])

In [21]:
myArr = np.array([0, 1, 2, 3, 4, 5])
print(myArr)

[0 1 2 3 4 5]


In [22]:
np.array([0, 1, 2, 3, 4, 5],ndmin=2)

array([[0, 1, 2, 3, 4, 5]])

Write the code to create 2d array (a)
with [10,11,12,13,14], [15,16,17,18,19] and output should print the 1st row 3rd column element and 2nd row 2nd column element.

In [29]:
a= np.array([[10,11,12,13,14],[15,16,17,18,19]])
print(a[0,2] , a[1,1])

12 16


 ## FromFunction   
 fromfunction(function, shape, dtype)

In [2]:
import numpy as np
a1= np.fromfunction(lambda i,j : i, (2,2), dtype= int)
a1

array([[0, 0],
       [1, 1]])

In [3]:
a2= np.fromfunction(lambda i,j : j, (2,2), dtype= int)
a2

array([[0, 1],
       [0, 1]])

In [4]:
a3= np.fromfunction(lambda i,j : i==j, (2,2), dtype= int)
a3

array([[ True, False],
       [False,  True]])

In [5]:
np.array(["string","yash", 4, 4.6]).dtype

dtype('<U32')

In [6]:
np.array([2.4, 3.5]).dtype

dtype('float64')

Write code to create array through the Conversion python structures with values as "10, 20, 30, 40, 50, 60" with following conditions:
1. Create array from:
a. list
b. tuple(the length of tuple must be 2)
c. set
2. Single print statement to show output with format as "Elements, type of the array, dimensionality of the array, shape of the array" in a user readable way.

In [14]:
import numpy as np
l= [10,20,30,40,50,60]
a= np.array(l)
print(f'{a} \n {a.ndim} \n {a.shape} \n {type(a)}')

[10 20 30 40 50 60] 
 1 
 (6,) 
 <class 'numpy.ndarray'>


In [16]:
a1= np.linspace(4,6,10)
a1

array([4.        , 4.22222222, 4.44444444, 4.66666667, 4.88888889,
       5.11111111, 5.33333333, 5.55555556, 5.77777778, 6.        ])

In [19]:
myArr = np.array([0, 1, 2, 3])
arr = myArr.astype(bool)
print(arr)

[False  True  True  True]


Write the code that creates an array which contains 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 . Create an 1-D array and then convert it to display as 3 rows of elements and 4 columns of elements.


In [26]:
a= np.arange(12)
print(a)
print(a.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## EDA Projecct  - 10/8/2022

In [2]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
ar = np.array(my_matrix)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print(np.arange(1,10))
print(np.arange(2,10,2))

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [19]:
print(np.zeros([3,3], dtype = int))
print(np.ones([3,3], dtype = int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [23]:
print(np.linspace(0,10,3))
print(np.linspace(0,10,10))

[ 0.  5. 10.]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [34]:
print(np.eye(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.56970049 0.29955756 0.89128627]
 [0.91021683 0.16532434 0.58937656]
 [0.59123917 0.84007819 0.72910588]]
[11  9]


In [36]:
print(np.random.rand(3,3))
print(np.random.randint(0,20,10))

[[0.02797687 0.91991828 0.5047907 ]
 [0.85504062 0.87701338 0.0765977 ]
 [0.09583795 0.57909485 0.07136292]]
[16  0 17 12  2  0  7 13  7  3]


In [38]:
ar = np.arange(0,9)
np.reshape(ar,[3,3]) # ar.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
arr = np.arange(0,50,2)
print(arr.reshape(1,25))
print(arr.reshape(25,1))

[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
  48]]
[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]
 [22]
 [24]
 [26]
 [28]
 [30]
 [32]
 [34]
 [36]
 [38]
 [40]
 [42]
 [44]
 [46]
 [48]]
